// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB1YVOALYz6uugoxPKK50uD17Hm_b1XEpo',
    appId: '1:870636838220:web:19629831b7821c13cc43e9',
    messagingSenderId: '870636838220',
    projectId: 'cashew-e7c3f',
    authDomain: 'cashew-e7c3f.firebaseapp.com',
    storageBucket: 'cashew-e7c3f.firebasestorage.app',
    measurementId: 'G-YP25RDRV6D',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQl7emal5kaAY4xWsSYInPQV_kag5VCgw',
    appId: '1:870636838220:android:a57eb6aeea3750b1cc43e9',
    messagingSenderId: '870636838220',
    projectId: 'cashew-e7c3f',
    storageBucket: 'cashew-e7c3f.firebasestorage.app',
  );
  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDD3NlkzBPqs6DGiyDt9yU77j0h_3RXYJo',
    appId: '1:870636838220:ios:d4e7151b3c61e40ecc43e9',
    messagingSenderId: '870636838220',
    projectId: 'cashew-e7c3f',
    storageBucket: 'cashew-e7c3f.firebasestorage.app',
    androidClientId: '870636838220-2ga2rdgbabl9imp3auu8mssgvpc395ku.apps.googleusercontent.com',
    iosClientId: '870636838220-aitrs5mn9mkl7fv0728q5gpjr00c3img.apps.googleusercontent.com',
    iosBundleId: 'com.budget.budget.RunnerTests',
  );
}
